### ISSUE TITLE
Fluentd becomes a zombie process

### ISSUE THREAD

**Issue by xidiandb** [fluent/fluentd#2949]
**Describe the bug**

In a production environment, our fluentd process becomes a zombie process.(defunct process)
We deployed the application using k8s.

**To Reproduce**

It has not yet been replicated in our test environment

**Expected behavior**

**Your Environment**

- Fluentd or td-agent version: `fluentd --version` or `td-agent --version`
`fluentd v1.7.4`
- Operating system: `cat /etc/os-release`
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
- Kernel version: `uname -r`
```4.15.0-45-generic```
If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
     <source>
      @type systemd
      @label @syslog
      matches []
      path /var/log/journal/
      tag systemd.system
      <storage>
        @type local
        persistent true
        path /var/log/es-systemd_syslog.json
      </storage>
      <entry>
        field_map {"MESSAGE": "Payload", "_SYSTEMD_UNIT": "service", "_CMDLINE": "Process"}
        field_map_strict true
      </entry>
    </source>
    <label @syslog>
    <filter *.system>
      @type grep
      <exclude>
        key service
        pattern /kubelet.service|docker.service|etcd.service/
      </exclude>
    </filter>
    <match **>
      @id forward
      @type forward
      expire_dns_cache 60
      ignore_network_errors_at_startup true
      slow_flush_log_threshold 120.0
      heartbeat_type none
      compress gzip
      <server>
        host fluentd-kafka
        port 24224
      </server>
      <buffer>
        @type file_single
        path /fluentd/log
        total_limit_size 2G
        chunk_limit_size 10M
        retry_type periodic
        retry_wait 60
        flush_mode interval
        flush_interval 60s
        flush_thread_count 2
        retry_forever true
        overflow_action block
      </buffer>
    </match>
```

**Your Error Log**

```
<3>2020-04-04T04:46:39.711078+08:00 mgt12 kernel: [61746.126852] INFO: task event_loop:16155 blocked for more than 120 seconds.
<3>2020-04-04T04:46:39.711105+08:00 mgt12 kernel: [61746.127168]       Not tainted 4.15.0-45-generic #48-Ubuntu
<3>2020-04-04T04:46:39.711107+08:00 mgt12 kernel: [61746.127357] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
<6>2020-04-04T04:46:39.711108+08:00 mgt12 kernel: [61746.127510] event_loop      D    0 16155  14680 0x00000000
<4>2020-04-04T04:46:39.711110+08:00 mgt12 kernel: [61746.127513] Call Trace:
<4>2020-04-04T04:46:39.711110+08:00 mgt12 kernel: [61746.127571]  __schedule+0x291/0x8a0
<4>2020-04-04T04:46:39.711112+08:00 mgt12 kernel: [61746.127575]  schedule+0x2c/0x80
<4>2020-04-04T04:46:39.711113+08:00 mgt12 kernel: [61746.127579]  schedule_timeout+0x1cf/0x350
<4>2020-04-04T04:46:39.711114+08:00 mgt12 kernel: [61746.127599]  ? kvm_sched_clock_read+0x1e/0x30
<4>2020-04-04T04:46:39.711116+08:00 mgt12 kernel: [61746.127605]  ? sched_clock+0x9/0x10
<4>2020-04-04T04:46:39.711117+08:00 mgt12 kernel: [61746.127609]  ? x2apic_send_IPI+0x4a/0x50
<4>2020-04-04T04:46:39.711118+08:00 mgt12 kernel: [61746.127611]  wait_for_completion+0xba/0x140
<4>2020-04-04T04:46:39.711119+08:00 mgt12 kernel: [61746.127619]  ? wake_up_q+0x80/0x80
<4>2020-04-04T04:46:39.711120+08:00 mgt12 kernel: [61746.127631]  flush_work+0x126/0x1e0
<4>2020-04-04T04:46:39.711121+08:00 mgt12 kernel: [61746.127634]  ? worker_detach_from_pool+0xa0/0xa0
<4>2020-04-04T04:46:39.711122+08:00 mgt12 kernel: [61746.127637]  flush_delayed_work+0x3f/0x50
<4>2020-04-04T04:46:39.711123+08:00 mgt12 kernel: [61746.127654]  fsnotify_wait_marks_destroyed+0x15/0x20
<4>2020-04-04T04:46:39.711124+08:00 mgt12 kernel: [61746.127656]  fsnotify_destroy_group+0x48/0xd0
<4>2020-04-04T04:46:39.711268+08:00 mgt12 kernel: [61746.127658]  inotify_release+0x1e/0x50
<4>2020-04-04T04:46:39.711275+08:00 mgt12 kernel: [61746.127666]  __fput+0xea/0x220
<4>2020-04-04T04:46:39.711277+08:00 mgt12 kernel: [61746.127668]  ____fput+0xe/0x10
<4>2020-04-04T04:46:39.711278+08:00 mgt12 kernel: [61746.127670]  task_work_run+0x9d/0xc0
<4>2020-04-04T04:46:39.711279+08:00 mgt12 kernel: [61746.127680]  exit_to_usermode_loop+0xc0/0xd0
<4>2020-04-04T04:46:39.711280+08:00 mgt12 kernel: [61746.127682]  do_syscall_64+0x115/0x130
<4>2020-04-04T04:46:39.711282+08:00 mgt12 kernel: [61746.127685]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
<4>2020-04-04T04:46:39.711283+08:00 mgt12 kernel: [61746.127696] RIP: 0033:0x7fd03fdb25d7
<4>2020-04-04T04:46:39.711284+08:00 mgt12 kernel: [61746.127697] RSP: 002b:00007fd036ffb760 EFLAGS: 00000293 ORIG_RAX: 0000000000000003
<4>2020-04-04T04:46:39.711286+08:00 mgt12 kernel: [61746.127699] RAX: 0000000000000000 RBX: 0000000000000012 RCX: 00007fd03fdb25d7
<4>2020-04-04T04:46:39.711288+08:00 mgt12 kernel: [61746.127700] RDX: 0000000000000000 RSI: 00007fd0401266ec RDI: 0000000000000012
<4>2020-04-04T04:46:39.711290+08:00 mgt12 kernel: [61746.127701] RBP: 00007fd036ffde80 R08: 0000000000000218 R09: 00007fd036ffdf60
<4>2020-04-04T04:46:39.711291+08:00 mgt12 kernel: [61746.127702] R10: 00007fd03f4008c0 R11: 0000000000000293 R12: 000000000000000b
<4>2020-04-04T04:46:39.711293+08:00 mgt12 kernel: [61746.127703] R13: 00007fd036ffb7d0 R14: 0000000000000000 R15: 00007fd036ffb8d8
```

**Additional context**

There is another log before the event_loop
```
<3>2020-04-04T04:46:39.711301+08:00 mgt12 kernel: [61746.127888] INFO: task kworker/u32:1:24405 blocked for more than 120 seconds.
<3>2020-04-04T04:46:39.711303+08:00 mgt12 kernel: [61746.128086]       Not tainted 4.15.0-45-generic #48-Ubuntu
<3>2020-04-04T04:46:39.711305+08:00 mgt12 kernel: [61746.128242] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
<6>2020-04-04T04:46:39.711306+08:00 mgt12 kernel: [61746.128340] kworker/u32:1   D    0 24405      2 0x80000000
<6>2020-04-04T04:46:39.711307+08:00 mgt12 kernel: [61746.128347] Workqueue: events_unbound fsnotify_mark_destroy_workfn
<4>2020-04-04T04:46:39.711308+08:00 mgt12 kernel: [61746.128349] Call Trace:
<4>2020-04-04T04:46:39.711309+08:00 mgt12 kernel: [61746.128353]  __schedule+0x291/0x8a0
<4>2020-04-04T04:46:39.711310+08:00 mgt12 kernel: [61746.128356]  schedule+0x2c/0x80
<4>2020-04-04T04:46:39.711312+08:00 mgt12 kernel: [61746.128359]  schedule_timeout+0x1cf/0x350
<4>2020-04-04T04:46:39.711313+08:00 mgt12 kernel: [61746.128366]  ? select_idle_sibling+0x29/0x410
<4>2020-04-04T04:46:39.711314+08:00 mgt12 kernel: [61746.128368]  ? ttwu_do_activate+0x77/0x80
<4>2020-04-04T04:46:39.711316+08:00 mgt12 kernel: [61746.128370]  wait_for_completion+0xba/0x140
<4>2020-04-04T04:46:39.711318+08:00 mgt12 kernel: [61746.128371]  ? wake_up_q+0x80/0x80
<4>2020-04-04T04:46:39.711319+08:00 mgt12 kernel: [61746.128379]  __synchronize_srcu.part.13+0x85/0xb0
<4>2020-04-04T04:46:39.711321+08:00 mgt12 kernel: [61746.128382]  ? trace_raw_output_rcu_utilization+0x50/0x50
<4>2020-04-04T04:46:39.711323+08:00 mgt12 kernel: [61746.128384]  ? x2apic_send_IPI+0x4a/0x50
<4>2020-04-04T04:46:39.711325+08:00 mgt12 kernel: [61746.128386]  synchronize_srcu+0x66/0xe0
<4>2020-04-04T04:46:39.711326+08:00 mgt12 kernel: [61746.128388]  ? synchronize_srcu+0x66/0xe0
<4>2020-04-04T04:46:39.711329+08:00 mgt12 kernel: [61746.128390]  fsnotify_mark_destroy_workfn+0x7b/0xe0
<4>2020-04-04T04:46:39.711331+08:00 mgt12 kernel: [61746.128393]  process_one_work+0x1de/0x410
<4>2020-04-04T04:46:39.711332+08:00 mgt12 kernel: [61746.128405]  worker_thread+0x253/0x410
<4>2020-04-04T04:46:39.711333+08:00 mgt12 kernel: [61746.128409]  kthread+0x121/0x140
<4>2020-04-04T04:46:39.711335+08:00 mgt12 kernel: [61746.128410]  ? process_one_work+0x410/0x410
<4>2020-04-04T04:46:39.711348+08:00 mgt12 kernel: [61746.128412]  ? kthread_create_worker_on_cpu+0x70/0x70
<4>2020-04-04T04:46:39.711351+08:00 mgt12 kernel: [61746.128415]  ret_from_fork+0x35/0x40

```

**Comment by xidiandb** [comment]
Just a little bit of information

**Comment by repeatedly** [comment]
From your configuration, event_loop is used in only systemd plugin.
systemd's timer is very simple workload...

But why zombie process happens with docker and tini combination?
If parent process died unexpectedly, tini or init handles forked process, right?

**Comment by xidiandb** [comment]
I wonder if it has something to do with the kernel，Every time fluentd becomes a zombie, it also becomes a zombie with the systemd process sd-pam.Their parent processes are in state D
like:
[#10123](https://github.com/systemd/systemd/issues/10123)

**Comment by nokute78** [comment]
Just FYI

```
<6>2020-04-04T04:46:39.711307+08:00 mgt12 kernel: [61746.128347] Workqueue: events_unbound fsnotify_mark_destroy_workfn
```

Hung in `fsnotify_mark_destroy_workfn` is reported by syzkaller.
It seems to be caused by several reasons.
https://syzkaller.appspot.com/bug?id=14b65db051ef5a1bacdb6c0b573ff905308784b1

One of them is fixed by this kernel patch. It fixes RTC driver.
However the patch is merged from v5.5. (It is greater than Ubuntu 20.04 which kernel is v5.4)
https://github.com/torvalds/linux/commit/7e7c005b4b1f1f169bcc4b2c3a40085ecc663df2#diff-de7896f0a3e222102b0cb5bda6c51e9a

**Comment by splitice** [comment]
While this is almost without doubt a kernel issue it's worth noting that this is still an issue as of kernel v5.7.6

```
[ 8337.757914] task:kworker/u2:2    state:D stack:    0 pid: 6254 ppid:     2 flags:0x00004000
[ 8337.758174] Workqueue: events_unbound fsnotify_mark_destroy_workfn
[ 8337.758408] Call Trace:
[ 8337.758663]  __schedule+0x267/0x7a0
[ 8337.758903]  schedule+0x3c/0xa0
[ 8337.759143]  schedule_timeout+0x20b/0x2a0
[ 8337.759399]  ? add_timer+0x13c/0x1f0
[ 8337.759632]  ? __update_load_avg_se+0x298/0x320
[ 8337.759859]  wait_for_completion+0x8c/0xf0
[ 8337.760161]  __synchronize_srcu.part.20+0x81/0xb0
[ 8337.760397]  ? __bpf_trace_rcu_utilization+0x10/0x10
[ 8337.760626]  ? synchronize_srcu+0xa9/0xf0
[ 8337.760850]  fsnotify_mark_destroy_workfn+0x74/0xf0
[ 8337.761089]  process_one_work+0x1a4/0x340
[ 8337.761394]  worker_thread+0x30/0x370
[ 8337.761671]  ? process_one_work+0x340/0x340
[ 8337.761899]  kthread+0x117/0x130
[ 8337.762165]  ? kthread_create_worker_on_cpu+0x70/0x70
[ 8337.762397]  ret_from_fork+0x1f/0x30
```
